<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            [
                'title' => 'RACINE BY GANDA - Mode Africaine Contemporaine',
                'slug' => 'home',
                'meta_title' => 'RACINE BY GANDA - Mode Africaine Contemporaine',
                'meta_description' => 'Découvrez des créations uniques qui célèbrent notre héritage africain. Des pièces artisanales confectionnées par les meilleurs créateurs africains.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => false,
                'published_at' => now(),
            ],
            [
                'title' => 'Notre Boutique',
                'slug' => 'boutique',
                'meta_title' => 'Boutique - RACINE BY GANDA',
                'meta_description' => 'Découvrez nos créations uniques inspirées du patrimoine africain. Mode, accessoires et art de vivre.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => true,
                'show_in_footer' => false,
                'published_at' => now(),
            ],
            [
                'title' => 'Showroom',
                'slug' => 'showroom',
                'meta_title' => 'Showroom - RACINE BY GANDA',
                'meta_description' => 'Visitez notre showroom et découvrez nos collections en exclusivité.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => true,
                'show_in_footer' => false,
                'published_at' => now(),
            ],
            [
                'title' => 'Notre Atelier',
                'slug' => 'atelier',
                'meta_title' => 'Atelier - RACINE BY GANDA',
                'meta_description' => 'Découvrez notre atelier de création et notre processus artisanal.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => true,
                'show_in_footer' => false,
                'published_at' => now(),
            ],
            [
                'title' => 'Nos Créateurs',
                'slug' => 'createurs',
                'meta_title' => 'Nos Créateurs - RACINE BY GANDA',
                'meta_description' => 'Rencontrez les créateurs talentueux qui façonnent l\'identité de RACINE BY GANDA.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => true,
                'show_in_footer' => false,
                'published_at' => now(),
            ],
            [
                'title' => 'Marketplace Créateurs',
                'slug' => 'marketplace',
                'meta_title' => 'Marketplace - RACINE BY GANDA',
                'meta_description' => 'Découvrez les créations uniques de nos stylistes partenaires.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => true,
                'show_in_footer' => false,
                'published_at' => now(),
            ],
            [
                'title' => 'Nos Événements',
                'slug' => 'evenements',
                'meta_title' => 'Événements - RACINE BY GANDA',
                'meta_description' => 'Découvrez nos défilés, expositions et rencontres.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => false,
                'published_at' => now(),
            ],
            [
                'title' => 'Portfolio',
                'slug' => 'portfolio',
                'meta_title' => 'Portfolio - RACINE BY GANDA',
                'meta_description' => 'Explorez notre portfolio de créations et réalisations.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => false,
                'published_at' => now(),
            ],
            [
                'title' => 'Albums Photos',
                'slug' => 'albums',
                'meta_title' => 'Albums Photos - RACINE BY GANDA',
                'meta_description' => 'Parcourez nos albums photos et découvrez nos collections en images.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => false,
                'published_at' => now(),
            ],
            [
                'title' => 'Amira Ganda - Fondatrice & CEO',
                'slug' => 'amira-ganda',
                'meta_title' => 'Amira Ganda - Fondatrice & CEO - RACINE BY GANDA',
                'meta_description' => 'Découvrez le parcours et la vision d\'Amira Ganda, fondatrice de RACINE BY GANDA.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => false,
                'published_at' => now(),
            ],
            [
                'title' => 'Aide & Support',
                'slug' => 'aide',
                'meta_title' => 'Aide & Support - RACINE BY GANDA',
                'meta_description' => 'Trouvez des réponses à vos questions et obtenez de l\'aide.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => true,
                'published_at' => now(),
            ],
            [
                'title' => 'Livraison',
                'slug' => 'livraison',
                'meta_title' => 'Livraison - RACINE BY GANDA',
                'meta_description' => 'Informations sur nos options de livraison et délais.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => true,
                'published_at' => now(),
            ],
            [
                'title' => 'Retours & Échanges',
                'slug' => 'retours-echanges',
                'meta_title' => 'Retours & Échanges - RACINE BY GANDA',
                'meta_description' => 'Politique de retours et d\'échanges de RACINE BY GANDA.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => true,
                'published_at' => now(),
            ],
            [
                'title' => 'Contact',
                'slug' => 'contact',
                'meta_title' => 'Contact - RACINE BY GANDA',
                'meta_description' => 'Contactez-nous pour toute question ou demande d\'information.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => true,
                'published_at' => now(),
            ],
            [
                'title' => 'À Propos',
                'slug' => 'a-propos',
                'meta_title' => 'À Propos - RACINE BY GANDA',
                'meta_description' => 'Découvrez l\'histoire de RACINE BY GANDA, notre mission et nos valeurs.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => true,
                'published_at' => now(),
            ],
            [
                'title' => 'Conditions Générales de Vente',
                'slug' => 'cgv',
                'meta_title' => 'CGV - RACINE BY GANDA',
                'meta_description' => 'Conditions générales de vente de RACINE BY GANDA.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => true,
                'published_at' => now(),
            ],
            [
                'title' => 'Confidentialité',
                'slug' => 'confidentialite',
                'meta_title' => 'Politique de Confidentialité - RACINE BY GANDA',
                'meta_description' => 'Politique de confidentialité et protection des données personnelles.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => true,
                'published_at' => now(),
            ],
            [
                'title' => 'Mentions Légales',
                'slug' => 'mentions-legales',
                'meta_title' => 'Mentions Légales - RACINE BY GANDA',
                'meta_description' => 'Mentions légales du site RACINE BY GANDA.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => true,
                'published_at' => now(),
            ],
            [
                'title' => 'FAQ',
                'slug' => 'faq',
                'meta_title' => 'FAQ - RACINE BY GANDA',
                'meta_description' => 'Questions fréquemment posées sur RACINE BY GANDA.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => true,
                'published_at' => now(),
            ],
            [
                'title' => 'Devenir Créateur',
                'slug' => 'devenir-createur',
                'meta_title' => 'Devenir Créateur - RACINE BY GANDA',
                'meta_description' => 'Rejoignez la marketplace RACINE BY GANDA en tant que créateur partenaire.',
                'status' => 'published',
                'template' => 'default',
                'show_in_header' => false,
                'show_in_footer' => false,
                'published_at' => now(),
            ],
        ];

        foreach ($pages as $page) {
            Page::updateOrCreate(['slug' => $page['slug']], $page);
        }

        $this->command->info('✅ ' . Page::count() . ' pages CMS créées/mises à jour !');
    }
}
