<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // ═══════════════════════════════════════
            // GROUPE : GÉNÉRAL
            // ═══════════════════════════════════════
            [
                'key' => 'site_name',
                'value' => 'RACINE BY GANDA',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Nom du site',
                'description' => 'Nom affiché sur tout le site',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'site_email',
                'value' => 'contact@racinebyganda.com',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Email de contact',
                'description' => 'Email principal pour les notifications',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'site_phone',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Téléphone',
                'description' => 'Numéro de contact affiché',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'site_address',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Adresse physique',
                'description' => 'Adresse du magasin/bureau',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'site_country',
                'value' => 'Cameroun',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Pays',
                'description' => 'Pays principal d\'activité',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'site_timezone',
                'value' => 'Africa/Douala',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Fuseau horaire',
                'description' => 'Fuseau horaire du site',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'social_facebook',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Facebook',
                'description' => 'URL de la page Facebook',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'social_instagram',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Instagram',
                'description' => 'URL du profil Instagram',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'social_twitter',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Twitter/X',
                'description' => 'URL du profil Twitter/X',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'social_whatsapp',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'label' => 'WhatsApp Business',
                'description' => 'Numéro WhatsApp Business',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'social_tiktok',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'label' => 'TikTok',
                'description' => 'URL du profil TikTok',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'social_linkedin',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'label' => 'LinkedIn',
                'description' => 'URL de la page LinkedIn',
                'is_encrypted' => false,
                'is_public' => true,
            ],

            // ═══════════════════════════════════════
            // GROUPE : MARKETPLACE
            // ═══════════════════════════════════════
            [
                'key' => 'commission_rate',
                'value' => '15.00',
                'type' => 'float',
                'group' => 'marketplace',
                'label' => 'Taux de commission par défaut (%)',
                'description' => 'Commission prélevée sur les ventes des créateurs marketplace',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'shipping_fee',
                'value' => '2000',
                'type' => 'integer',
                'group' => 'marketplace',
                'label' => 'Frais de livraison par défaut (FCFA)',
                'description' => 'Frais de livraison standard',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'currency',
                'value' => 'FCFA',
                'type' => 'string',
                'group' => 'marketplace',
                'label' => 'Devise',
                'description' => 'Devise principale du site',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'low_stock_threshold',
                'value' => '10',
                'type' => 'integer',
                'group' => 'marketplace',
                'label' => 'Seuil stock faible',
                'description' => 'Alerte si stock inférieur à cette valeur',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'low_stock_critical',
                'value' => '3',
                'type' => 'integer',
                'group' => 'marketplace',
                'label' => 'Seuil stock critique',
                'description' => 'Alerte rouge si stock inférieur à cette valeur',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'auto_reorder_enabled',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'marketplace',
                'label' => 'Réapprovisionnement automatique',
                'description' => 'Activer le réapprovisionnement auto des produits',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'free_shipping_threshold',
                'value' => '50000',
                'type' => 'integer',
                'group' => 'marketplace',
                'label' => 'Livraison gratuite à partir de (FCFA)',
                'description' => 'Montant minimum pour livraison gratuite',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'order_auto_cancel_hours',
                'value' => '24',
                'type' => 'integer',
                'group' => 'marketplace',
                'label' => 'Annulation auto commande non payée (heures)',
                'description' => 'Délai avant annulation automatique (0 = désactivé)',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'max_variants_per_product',
                'value' => '20',
                'type' => 'integer',
                'group' => 'marketplace',
                'label' => 'Nombre max de variantes par produit',
                'description' => 'Limite de variantes autorisées par produit',
                'is_encrypted' => false,
                'is_public' => false,
            ],


            // ═══════════════════════════════════════
            // GROUPE : PAYMENTS
            // ═══════════════════════════════════════
            [
                'key' => 'stripe_mode',
                'value' => 'test',
                'type' => 'string',
                'group' => 'payments',
                'label' => 'Mode Stripe',
                'description' => 'Mode test ou production pour Stripe',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'payments_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'payments',
                'label' => 'Paiements en ligne activés',
                'description' => 'Autoriser ou bloquer les paiements en ligne',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'stripe_currency',
                'value' => 'EUR',
                'type' => 'string',
                'group' => 'payments',
                'label' => 'Devise Stripe',
                'description' => 'Devise utilisée pour les paiements Stripe',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'monetbil_auto_approve_threshold',
                'value' => '0',
                'type' => 'integer',
                'group' => 'payments',
                'label' => 'Auto-approuver paiements Monetbil < X FCFA',
                'description' => '0 = validation manuelle toujours requise',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'payment_max_attempts',
                'value' => '3',
                'type' => 'integer',
                'group' => 'payments',
                'label' => 'Tentatives max par paiement',
                'description' => 'Nombre de tentatives autorisées avant blocage',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'payment_retry_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'payments',
                'label' => 'Retry automatique sur échec paiement',
                'description' => 'Réessayer automatiquement les paiements échoués',
                'is_encrypted' => false,
                'is_public' => false,
            ],

            // ═══════════════════════════════════════
            // GROUPE : EMAIL
            // ═══════════════════════════════════════
            [
                'key' => 'mail_from_name',
                'value' => 'RACINE BY GANDA',
                'type' => 'string',
                'group' => 'email',
                'label' => 'Nom expéditeur',
                'description' => 'Nom affiché comme expéditeur des emails',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'mail_from_address',
                'value' => 'contact@racinebyganda.com',
                'type' => 'string',
                'group' => 'email',
                'label' => 'Email expéditeur',
                'description' => 'Adresse email expéditeur (From)',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'admin_notification_email',
                'value' => '',
                'type' => 'string',
                'group' => 'email',
                'label' => 'Email notifications admin',
                'description' => 'Email de destination des notifications admin',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'admin_notification_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'email',
                'label' => 'Notifications email admin activées',
                'description' => 'Recevoir les notifications admin par email',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'mail_logo_url',
                'value' => '',
                'type' => 'string',
                'group' => 'email',
                'label' => 'URL logo dans emails',
                'description' => 'URL du logo utilisé dans les templates email',
                'is_encrypted' => false,
                'is_public' => false,
            ],

            // ═══════════════════════════════════════
            // GROUPE : INTEGRATIONS
            // ═══════════════════════════════════════
            [
                'key' => 'google_oauth_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'integrations',
                'label' => 'Google OAuth activé',
                'description' => 'Autoriser la connexion via Google',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'google_redirect_uri',
                'value' => '',
                'type' => 'string',
                'group' => 'integrations',
                'label' => 'URI de redirection Google OAuth',
                'description' => 'Ex: https://racinebyganda.com/auth/google/callback',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'recaptcha_enabled',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'integrations',
                'label' => 'reCAPTCHA activé',
                'description' => 'Activer la protection reCAPTCHA v3',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'recaptcha_threshold',
                'value' => '0.5',
                'type' => 'float',
                'group' => 'integrations',
                'label' => 'Score minimum reCAPTCHA (0.0-1.0)',
                'description' => '0.0 = permissif, 1.0 = strict',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'openai_enabled',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'integrations',
                'label' => 'OpenAI/Amira activé',
                'description' => 'Activer le module IA Amira',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'openai_model',
                'value' => 'gemini-2.0-flash',
                'type' => 'string',
                'group' => 'integrations',
                'label' => 'Modèle IA par défaut',
                'description' => 'Ex: gpt-4o-mini, gemini-2.0-flash, claude-3-haiku',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'openai_max_tokens',
                'value' => '1000',
                'type' => 'integer',
                'group' => 'integrations',
                'label' => 'Max tokens par requête',
                'description' => 'Limite de tokens générés par requête IA',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'openai_temperature',
                'value' => '0.7',
                'type' => 'float',
                'group' => 'integrations',
                'label' => 'Température génération IA',
                'description' => '0 = déterministe, 1 = créatif',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'amira_provider',
                'value' => 'openai',
                'type' => 'string',
                'group' => 'integrations',
                'label' => 'Provider IA',
                'description' => 'Provider IA : openai/gemini/anthropic',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'sentry_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'integrations',
                'label' => 'Sentry monitoring activé',
                'description' => 'Activer le monitoring Sentry',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'sentry_traces_rate',
                'value' => '0.1',
                'type' => 'float',
                'group' => 'integrations',
                'label' => 'Taux échantillonnage traces Sentry',
                'description' => '0.1 = 10% des requêtes',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'exchange_rate_cache_ttl',
                'value' => '24',
                'type' => 'integer',
                'group' => 'integrations',
                'label' => 'Cache taux de change (heures)',
                'description' => 'Durée de cache des taux de change',
                'is_encrypted' => false,
                'is_public' => false,
            ],

            // ═══════════════════════════════════════
            // GROUPE : SECURITY
            // ═══════════════════════════════════════
            [
                'key' => 'force_2fa_admin',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'security',
                'label' => 'Forcer 2FA pour admins',
                'description' => 'Rendre le 2FA obligatoire pour tous les admins',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'force_2fa_creator',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'security',
                'label' => 'Forcer 2FA pour créateurs',
                'description' => 'Rendre le 2FA obligatoire pour les créateurs',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'session_timeout',
                'value' => '120',
                'type' => 'integer',
                'group' => 'security',
                'label' => 'Timeout session (minutes)',
                'description' => 'Déconnexion automatique après inactivité',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'max_concurrent_sessions',
                'value' => '5',
                'type' => 'integer',
                'group' => 'security',
                'label' => 'Sessions simultanées max',
                'description' => 'Nombre max de sessions par utilisateur',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'login_max_attempts',
                'value' => '5',
                'type' => 'integer',
                'group' => 'security',
                'label' => 'Tentatives login max',
                'description' => 'Tentatives avant blocage',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'login_lockout_minutes',
                'value' => '15',
                'type' => 'integer',
                'group' => 'security',
                'label' => 'Durée blocage après échec (minutes)',
                'description' => 'Durée du blocage temporaire',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'password_min_length',
                'value' => '8',
                'type' => 'integer',
                'group' => 'security',
                'label' => 'Longueur min mot de passe',
                'description' => 'Nombre minimum de caractères',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'password_require_uppercase',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'security',
                'label' => 'Majuscule obligatoire',
                'description' => 'Exiger au moins une majuscule',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'password_require_numbers',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'security',
                'label' => 'Chiffre obligatoire',
                'description' => 'Exiger au moins un chiffre',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'password_require_special',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'security',
                'label' => 'Caractère spécial obligatoire',
                'description' => 'Exiger au moins un caractère spécial (!@#$...)',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'password_expiry_days',
                'value' => '0',
                'type' => 'integer',
                'group' => 'security',
                'label' => 'Expiration mot de passe (jours)',
                'description' => '0 = jamais',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'trusted_device_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'security',
                'label' => 'Appareils de confiance activés',
                'description' => 'Permettre de marquer un appareil comme confiance',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'trusted_device_days',
                'value' => '30',
                'type' => 'integer',
                'group' => 'security',
                'label' => 'Durée confiance appareil (jours)',
                'description' => 'Durée avant expiration de la confiance',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'ip_whitelist_enabled',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'security',
                'label' => 'Whitelist IP admin activée',
                'description' => 'Restreindre l\'accès admin par IP',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'ip_whitelist',
                'value' => '',
                'type' => 'string',
                'group' => 'security',
                'label' => 'IPs autorisées',
                'description' => 'IPs autorisées séparées par virgule',
                'is_encrypted' => false,
                'is_public' => false,
            ],

            // ═══════════════════════════════════════
            // GROUPE : APPEARANCE
            // ═══════════════════════════════════════
            [
                'key' => 'logo_url',
                'value' => '',
                'type' => 'string',
                'group' => 'appearance',
                'label' => 'URL du logo principal',
                'description' => 'Format recommandé : SVG ou PNG transparent, 200x60px',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'logo_dark_url',
                'value' => '',
                'type' => 'string',
                'group' => 'appearance',
                'label' => 'URL du logo mode sombre',
                'description' => 'Logo alternatif pour le mode sombre',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'favicon_url',
                'value' => '',
                'type' => 'string',
                'group' => 'appearance',
                'label' => 'URL du favicon',
                'description' => 'Format : ICO ou PNG 32x32px',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'primary_color',
                'value' => '#ED5F1E',
                'type' => 'string',
                'group' => 'appearance',
                'label' => 'Couleur primaire (orange)',
                'description' => 'Charte RACINE BY GANDA - Ne pas modifier',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'secondary_color',
                'value' => '#FFB800',
                'type' => 'string',
                'group' => 'appearance',
                'label' => 'Couleur secondaire (jaune)',
                'description' => 'Charte RACINE BY GANDA - Ne pas modifier',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'dark_color',
                'value' => '#160D0C',
                'type' => 'string',
                'group' => 'appearance',
                'label' => 'Couleur sombre (noir)',
                'description' => 'Charte RACINE BY GANDA - Ne pas modifier',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'default_theme',
                'value' => 'dark',
                'type' => 'string',
                'group' => 'appearance',
                'label' => 'Thème par défaut',
                'description' => 'Thème par défaut pour nouveaux utilisateurs',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'default_accent',
                'value' => 'orange',
                'type' => 'string',
                'group' => 'appearance',
                'label' => 'Palette accent par défaut',
                'description' => 'Palette accent par défaut pour nouveaux utilisateurs',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'animation_intensity',
                'value' => 'standard',
                'type' => 'string',
                'group' => 'appearance',
                'label' => 'Intensité animations',
                'description' => 'Intensité animations par défaut',
                'is_encrypted' => false,
                'is_public' => true,
            ],
            [
                'key' => 'custom_css',
                'value' => '',
                'type' => 'string',
                'group' => 'appearance',
                'label' => 'CSS personnalisé global',
                'description' => 'CSS appliqué sur toutes les pages admin',
                'is_encrypted' => false,
                'is_public' => false,
            ],




            // ═══════════════════════════════════════
            // GROUPE : ADVANCED
            // ═══════════════════════════════════════
            [
                'key' => 'registrations_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'advanced',
                'label' => 'Inscriptions publiques activées',
                'description' => 'Autoriser les nouvelles inscriptions sur le site',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'maintenance_message',
                'value' => '',
                'type' => 'string',
                'group' => 'advanced',
                'label' => 'Message de maintenance',
                'description' => 'Message affiché pendant la maintenance',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'maintenance_mode',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'advanced',
                'label' => 'Mode maintenance activé',
                'description' => 'Afficher page maintenance pour visiteurs',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'debug_mode',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'advanced',
                'label' => 'Mode debug (APP_DEBUG)',
                'description' => 'Informatif uniquement - géré par .env',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'log_level',
                'value' => 'error',
                'type' => 'string',
                'group' => 'advanced',
                'label' => 'Niveau de logs',
                'description' => 'Niveau minimum logs : debug/info/warning/error',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'log_channel',
                'value' => 'daily',
                'type' => 'string',
                'group' => 'advanced',
                'label' => 'Canal de logs',
                'description' => 'Canal logs : single/daily/stack',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'logs_retention_days',
                'value' => '30',
                'type' => 'integer',
                'group' => 'advanced',
                'label' => 'Rétention logs (jours)',
                'description' => 'Durée conservation logs',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'cache_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'advanced',
                'label' => 'Cache Redis activé',
                'description' => 'Activer cache Redis',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'queue_connection',
                'value' => 'redis',
                'type' => 'string',
                'group' => 'advanced',
                'label' => 'Connexion queue',
                'description' => 'Connexion queue : redis/database/sync',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'backup_enabled',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'advanced',
                'label' => 'Sauvegardes automatiques',
                'description' => 'Activer sauvegardes automatiques',
                'is_encrypted' => false,
                'is_public' => false,
            ],

            // ═══════════════════════════════════════
            // GROUPE : PROFILE
            // ═══════════════════════════════════════
            [
                'key' => 'admin_display_name',
                'value' => '',
                'type' => 'string',
                'group' => 'profile',
                'label' => 'Nom affiché',
                'description' => 'Nom affiché dans interface admin',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'admin_bio',
                'value' => '',
                'type' => 'string',
                'group' => 'profile',
                'label' => 'Biographie',
                'description' => 'Description / biographie admin',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'admin_language',
                'value' => 'fr',
                'type' => 'string',
                'group' => 'profile',
                'label' => 'Langue interface',
                'description' => 'Langue interface : fr/en',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'admin_avatar_url',
                'value' => '',
                'type' => 'string',
                'group' => 'profile',
                'label' => 'URL avatar admin',
                'description' => 'URL avatar admin',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'admin_notifications_email',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'profile',
                'label' => 'Notifications email activées',
                'description' => 'Recevoir notifications par email',
                'is_encrypted' => false,
                'is_public' => false,
            ],
            [
                'key' => 'admin_notifications_browser',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'profile',
                'label' => 'Notifications navigateur activées',
                'description' => 'Recevoir notifications navigateur',
                'is_encrypted' => false,
                'is_public' => false,
            ],

        ];

        foreach ($settings as $setting) {
            DB::table('settings')->updateOrInsert(
                ['key' => $setting['key']],
                array_merge($setting, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }

        $this->command->info('✅ ' . count($settings) . ' settings insérés/mis à jour');
    }
}